version: "3.9"
services:
    app:
        build:
            dockerfile: Dockerfile.dev
            context: .
            target: dev
        expose:
            -   80
        ports:
            -   "80:8080"
            -   "50051:50051"
        volumes:
            - .:/opt/app/api

    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            -   "3306:3306"
        volumes:
            -   mysql:/var/lib/mysql

    consul-server:
        image: hashicorp/consul:1.11.2
        container_name: consul-server
        restart: always
        volumes:
            - ./docker/consul.json:/consul/config/consul.json:ro
        ports:
            - "8500:8500"
            - "8600:8600/tcp"
            - "8600:8600/udp"
        command: "agent -dev"

    prometheus:
        image: prom/prometheus:v2.30.3
        ports:
            - 9000:9090
        volumes:
            - ./prometheus:/etc/prometheus
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
    mysql:
