version: "3.9"
services:
    app:
        build:
            dockerfile: Dockerfile.dev
            context: .
            target: dev
        ports:
            -   "80:8080"
        volumes:
            - .:/opt/app/api

    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            -   "3306:3306"
        volumes:
            -   mysql:/var/lib/mysql

volumes:
    mysql:
