version: "3.9"
services:
    app:
        build:
            dockerfile: Dockerfile.dev
            context: .
            target: dev
        ports:
            -   "80:8080"
        volumes:
            - .:/opt/app/api

    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            -   "3306:3306"
        volumes:
            -   mysql:/var/lib/mysql

    consul-server:
        image: hashicorp/consul:1.11.2
        container_name: consul-server
        restart: always
        volumes:
            - ./docker/consul.json:/consul/config/consul.json:ro
        ports:
            - "8500:8500"
            - "8600:8600/tcp"
            - "8600:8600/udp"
        command: "agent -dev"

volumes:
    mysql:
